//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.3615
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MITSUBISHI_PLC.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MITSUBISHI_PLC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   QCPU(Qﾓｰﾄﾞ),Q00JCPU,30,250,250
        ///QCPU(Qﾓｰﾄﾞ),Q00UJCPU,80,260,260
        ///QCPU(Qﾓｰﾄﾞ),Q00CPU,31,251,251
        ///QCPU(Qﾓｰﾄﾞ),Q00UCPU,81,261,261
        ///QCPU(Qﾓｰﾄﾞ),Q01CPU,32,252,252
        ///QCPU(Qﾓｰﾄﾞ),Q01UCPU,82,262,262
        ///QCPU(Qﾓｰﾄﾞ),Q02CPU,22,41,41
        ///QCPU(Qﾓｰﾄﾞ),Q02HCPU,22,41,41
        ///QCPU(Qﾓｰﾄﾞ),Q06HCPU,23,42,42
        ///QCPU(Qﾓｰﾄﾞ),Q12HCPU,24,43,43
        ///QCPU(Qﾓｰﾄﾞ),Q25HCPU,25,44,44
        ///QCPU(Qﾓｰﾄﾞ),Q02PHCPU,45,41,41
        ///QCPU(Qﾓｰﾄﾞ),Q06PHCPU,46,42,42
        ///QCPU(Qﾓｰﾄﾞ),Q12PHCPU,41,43,43
        ///QCPU(Qﾓｰﾄﾞ),Q25PHCPU,42,44,44
        ///QCPU(Qﾓｰﾄﾞ),Q12PRHCPU,43,4B,4B
        ///QCPU(Qﾓｰﾄﾞ),Q25P [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ActCpuTypeDataBase {
            get {
                return ResourceManager.GetString("ActCpuTypeDataBase", resourceCulture);
            }
        }
    }
}
